//
// Module Processor.control_pipelined.tbl
//
// Created:
//          by - tron.UNKNOWN (CISCOIX)
//          at - 23:51:21 02/12/2009
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module control_pipelined( 
   OpCode, 
   Zero, 
   Func, 
   LoadInst, 
   MemWt, 
   PCSource, 
   RdAddrSel, 
   RegWt, 
   WtDataSel
);


// Internal Declarations

input  [3:0] OpCode;
input        Zero;
output [2:0] Func;
output       LoadInst;
output       MemWt;
output       PCSource;
output       RdAddrSel;
output       RegWt;
output [1:0] WtDataSel;


wire [3:0] OpCode;
wire Zero;
reg [2:0] Func;
reg LoadInst;
reg MemWt;
reg PCSource;
reg RdAddrSel;
reg RegWt;
reg [1:0] WtDataSel;

// Local declarations
 

/////////////////////////////////////////////////////////////////
always @ (OpCode or Zero) begin : truth_table_block_proc

   // Block 1
   if ((OpCode == 4'b0010))
      begin
         LoadInst = 1;
         MemWt = 0;
         PCSource = 0;
         RdAddrSel = 0;
         RegWt = 1;
         WtDataSel = 2'b10;
      end
   else if ((OpCode == 4'b0011))
      begin
         LoadInst = 1;
         MemWt = 0;
         PCSource = 0;
         RdAddrSel = 0;
         RegWt = 1;
         WtDataSel = 2'b01;
      end
   else if ((OpCode == 4'b0100))
      begin
         LoadInst = 1;
         MemWt = 1;
         PCSource = 0;
         RdAddrSel = 1;
         RegWt = 0;
         WtDataSel = 2'b00;
      end
   else if ((OpCode == 4'b0000))
      begin
         Func = 3'b010;
         LoadInst = 1;
         MemWt = 0;
         PCSource = 0;
         RdAddrSel = 0;
         RegWt = 1;
         WtDataSel = 2'b00;
      end
   else if ((OpCode == 4'b0001))
      begin
         Func = 3'b000;
         LoadInst = 1;
         MemWt = 0;
         PCSource = 0;
         RdAddrSel = 0;
         RegWt = 1;
         WtDataSel = 2'b00;
      end
   else if ((OpCode == 4'b1001))
      begin
         LoadInst = 1;
         MemWt = 0;
         PCSource = 1;
         RdAddrSel = 0;
         RegWt = 0;
         WtDataSel = 2'b00;
      end
   else if ((OpCode == 4'b1000) && (Zero == 0))
      begin
         LoadInst = 1;
         MemWt = 0;
         PCSource = 1;
         RdAddrSel = 1;
         RegWt = 0;
         WtDataSel = 2'b00;
      end
   else if ((OpCode == 4'b1000) && (Zero == 1))
      begin
         LoadInst = 1;
         MemWt = 0;
         PCSource = 0;
         RdAddrSel = 1;
         RegWt = 0;
         WtDataSel = 2'b00;
      end
end

endmodule // control_pipelined

